### ISSUE TITLE
Spotify doesn't find the app

### ISSUE THREAD

**Issue by samuelluis** [Linuus/spotitar#1]
![Screenshot](https://cloud.githubusercontent.com/assets/692450/5927092/a2027374-a646-11e4-981c-1ef7f0f1ce22.png)

Maybe the folder changed for this version of Spotify. Please help.

**Comment by Linuus** [comment]
What version do you have? Did it use to work?

I have version 0.9.15.27 and it works.

**Comment by samuelluis** [comment]
The folder `~/Spotify` should exist? because I had to create it, and I have exactly the same version of Spotify (0.9.15.27) and the search spotify:app:spotitar doesn't throw any results.

btw, I've been reading about Spotify has discontinued the Apps feature and now the apps work through the Web API (or mobile). This may be the problem I guess.

**Comment by samuelluis** [comment]
Apology, closed it by mistake.

**Comment by Linuus** [comment]
Yes, they will the turn off the app features soon. I don't think they have yet though. And it is, unfortunately, not possible to recreate Spotitar using the web api.

Are you registered as a developer at Spotify?

Yes, you should create the folder yourself.

**Comment by Linuus** [comment]
@samuelluis Did you resolve the issue?

**Comment by Linuus** [comment]
I'm closing for now. Reopen if you still have issues.
